service: cloudformation-rockset

custom:
  currentStage: ${{opt:stage, self:provider.stage}}
  resourceTags:
    - Key: "module"
      Value: "cloudformation-rockset"

provider:
  name: aws
  runtime: java8
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}" # notice the double quotes for yaml to ignore the escape characters!
  region: ca-central-1
  stage: staging
  stackName: ${{self:custom.currentStage}}-cloudformation-rockset-stack
  Tags: ${{self:custom.resourceTags}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: arn:aws:logs:*:*:*
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource: arn:aws:ssm:${{opt:region, self:provider.region}}:*:parameter/*-*-api-key
    - Effect: Allow
      Action:
        - iam:TagRole
        - iam:DeletePolicy
        - iam:CreateRole
        - iam:AttachRolePolicy
        - iam:DetachRolePolicy
        - iam:DeleteRolePolicy
        - iam:ListAttachedRolePolicies
        - iam:ListAttachedUserPolicies
        - iam:ListRolePolicies
        - iam:GetRole
        - iam:GetPolicy
        - iam:DeleteRole
        - iam:CreatePolicy
        - iam:GetUser
        - iam:GetRolePolicy
      Resource:
        - arn:aws:iam::*:policy/*
        - arn:aws:iam::*:role/*
    - Effect: Allow
      Action:
        - iam:ListPolicies
      Resource:
        - arn:aws:iam::*:role/*

package:
  artifact: build/distributions/cloudformation-rockset.zip

functions:
  RocksetIntegrationLambda:
    name: RocksetIntegration
    handler: ski.crunch.rockset.lambda.RocksetIntegrationLambda
    memorySize:  512
    timeout: 240
    environment:
      awsAccountId:
        Ref: AWS::AccountId
    Tags: ${{self:custom.resourceTags}}
  RocksetWorkspaceLambda:
    name: RocksetWorkspace
    handler: ski.crunch.rockset.lambda.RocksetWorkspaceLambda
    memorySize:  512
    timeout: 240
    Tags: ${{self:custom.resourceTags}}
  RocksetCollectionLambda:
    name: RocksetCollection
    handler: ski.crunch.rockset.lambda.RocksetCollectionLambda
    memorySize:  512
    timeout: 240
    Tags: ${{self:custom.resourceTags}}
resources:
  Resources:
    SsmParamForRocksetApiKey:
      Type: "AWS::SSM::Parameter"
      Properties:
        Name: "${{self:custom.currentStage}}-rockset-api-key"
        Type: "String"
        Value: "abc123"
        Description: "SSM Parameter for storing rockset api key"
  Outputs:
    RocksetIntegrationFunctionArn:
      Description: Rockset Integration Lambda Function ARN
      Value: !GetAtt 'RocksetIntegrationLambdaLambdaFunction.Arn'
      Export:
        Name:
          Fn::Join: ['',[ Ref: AWS::StackName,'-RocksetIntegrationFunction']]
    RocksetWorkspaceFunctionArn:
      Description: Rockset Workspace Lambda Function ARN
      Value: !GetAtt 'RocksetWorkspaceLambdaLambdaFunction.Arn'
      Export:
        Name:
          Fn::Join: ['',[ Ref: AWS::StackName,'-RocksetWorkspaceFunction']]
    RocksetCollectionFunctionArn:
      Description: Rockset Collection Lambda Function ARN
      Value: !GetAtt 'RocksetCollectionLambdaLambdaFunction.Arn'
      Export:
        Name:
          Fn::Join: ['',[ Ref: AWS::StackName,'-RocksetCollectionFunction']]
